name: Test

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: dbmigrate
          POSTGRES_PASSWORD: dbmigrate
          POSTGRES_DB: dbmigrate
        ports:
            - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...
